apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: "hello-world-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres
            - configMapRef:
                name: postgres
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgres-database-storage
      volumes:
        - name: postgres-database-storage
          persistentVolumeClaim:
            claimName: postgres-volume
